# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CertwatchWebhookCli < Formula
  desc "Deliver real CT certificate webhook payloads to your local endpoint"
  homepage "https://certwatch.app"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v1.0.0/certwatch-webhook-cli_darwin_amd64.tar.gz"
      sha256 "e304beb0c74c9a245c7d9cf102b5d6a31de1ac8b739563447f8566e0796db1cd"

      def install
        bin.install "certwatch-webhook-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v1.0.0/certwatch-webhook-cli_darwin_arm64.tar.gz"
      sha256 "78adc6343afb2bac521bb36362b860e8434882ebd59b9e263dbe0b44a9c57c2d"

      def install
        bin.install "certwatch-webhook-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v1.0.0/certwatch-webhook-cli_linux_amd64.tar.gz"
      sha256 "3f8af749daf18879fa095620ddd9550243fc61c6611d3f91c4f885cfdd10fc55"
      def install
        bin.install "certwatch-webhook-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v1.0.0/certwatch-webhook-cli_linux_arm64.tar.gz"
      sha256 "5d9774c79f733295f23ef22b51ea15e60de81a91be576bcb540a9c3894d322fe"
      def install
        bin.install "certwatch-webhook-cli"
      end
    end
  end
end
