# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CertwatchWebhookCli < Formula
  desc "Deliver real CT certificate webhook payloads to your local endpoint"
  homepage "https://certwatch.app"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v1.0.1/certwatch-webhook-cli_darwin_amd64.tar.gz"
      sha256 "ce318c41927561a6568c45620c5477a88addd193f648592431bbf9c56c7b8c32"

      def install
        bin.install "certwatch-webhook-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v1.0.1/certwatch-webhook-cli_darwin_arm64.tar.gz"
      sha256 "b82cca57b4415c8fd63834a6a3dee916b9f4abd1d5de1c5fe0d9827bc3effce2"

      def install
        bin.install "certwatch-webhook-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v1.0.1/certwatch-webhook-cli_linux_amd64.tar.gz"
      sha256 "c471828cb543299418c12aef79a4548e6666411514cc6a6493e54c929e5230d4"
      def install
        bin.install "certwatch-webhook-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v1.0.1/certwatch-webhook-cli_linux_arm64.tar.gz"
      sha256 "0af2f19bf90d7b27d24cf3143e22b74bbb5cac5694ee804444158ea28f424bc8"
      def install
        bin.install "certwatch-webhook-cli"
      end
    end
  end
end
