# This file was generated by GoReleaser. DO NOT EDIT.
cask "certwatch-webhook-cli" do
  name "certwatch-webhook-cli"
  desc "Deliver real CT certificate webhook payloads to your local endpoint"
  homepage "https://certwatch.app"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certwatch-webhook-cli"

  on_macos do
    on_intel do
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v#{version}/certwatch-webhook-cli_darwin_amd64.tar.gz"
      sha256 "a4c61138a944f81f250fc5e23eccc1bdf94d527eba3026ed566f85047dff3c58"
    end
    on_arm do
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v#{version}/certwatch-webhook-cli_darwin_arm64.tar.gz"
      sha256 "e3e9d1390a89f0a639b90f3b9a52435747375da9a956026af9bd24843eeb1863"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v#{version}/certwatch-webhook-cli_linux_amd64.tar.gz"
      sha256 "ba7147a8680d7eca7e518668b0742ed17d0fd132301b30480124197d071841cf"
    end
    on_arm do
      url "https://github.com/certwatch-app/certwatch-webhook-cli/releases/download/v#{version}/certwatch-webhook-cli_linux_arm64.tar.gz"
      sha256 "44fbb78eb52ace7931832ffe3105fbba5bf403678ea11c0427a4979f0e8d2f55"
    end
  end

  # No zap stanza required
end
