# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwAgent < Formula
  desc "SSL/TLS certificate monitoring agent for CertWatch"
  homepage "https://certwatch.app"
  version "0.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/certwatch-app/cw-agent/releases/download/v0.4.2/cw-agent_0.4.2_darwin_amd64.tar.gz"
      sha256 "40ebf3729c7f8b5ab8bbae8df6b3dcb1a719628386089a821d649347b81cac31"

      def install
        bin.install "cw-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/certwatch-app/cw-agent/releases/download/v0.4.2/cw-agent_0.4.2_darwin_arm64.tar.gz"
      sha256 "88f94eb382f2bed14665f0697a3998da7ece39d0f6bbe91e353a2c42f25b22ef"

      def install
        bin.install "cw-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/certwatch-app/cw-agent/releases/download/v0.4.2/cw-agent_0.4.2_linux_amd64.tar.gz"
      sha256 "2571e8be5db788f87aa2a66985a161767e82d73018964a2df0703914b97a1942"
      def install
        bin.install "cw-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/certwatch-app/cw-agent/releases/download/v0.4.2/cw-agent_0.4.2_linux_arm64.tar.gz"
      sha256 "bc98c44b53ce14146e085e5df85b9426796a4c692238153d595c4568880314c1"
      def install
        bin.install "cw-agent"
      end
    end
  end

  test do
    system "#{bin}/cw-agent", "version"
  end
end
