# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwAgent < Formula
  desc "SSL/TLS certificate monitoring agent for CertWatch"
  homepage "https://certwatch.app"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/certwatch-app/cw-agent/releases/download/v0.2.1/cw-agent_0.2.1_darwin_amd64.tar.gz"
      sha256 "799979ef69b2b9121912bdc0df9c6ba0d12364c0eebc68d02ff48336ccb80fb1"

      def install
        bin.install "cw-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/certwatch-app/cw-agent/releases/download/v0.2.1/cw-agent_0.2.1_darwin_arm64.tar.gz"
      sha256 "a1e1ed296e55316d5489557442a5ee239f82e008754389f56fb90eccccbd23c5"

      def install
        bin.install "cw-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/certwatch-app/cw-agent/releases/download/v0.2.1/cw-agent_0.2.1_linux_amd64.tar.gz"
      sha256 "b4acd7964f2e099c466081cc5700357b861a74e86280d0e5698b21183e2be322"
      def install
        bin.install "cw-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/certwatch-app/cw-agent/releases/download/v0.2.1/cw-agent_0.2.1_linux_arm64.tar.gz"
      sha256 "f401331930ce2a8ab17589933af742398950f2ff49f1677ed4f114205afc6060"
      def install
        bin.install "cw-agent"
      end
    end
  end

  test do
    system "#{bin}/cw-agent", "version"
  end
end
